# Generated by Django 2.0.5 on 2018-05-06 17:38

from django.db import migrations, models
import huawei.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAModel',
            fields=[
                ('md5', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('question', models.CharField(max_length=150, verbose_name='问题')),
                ('topic', models.CharField(max_length=32, verbose_name='主题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('expand', models.TextField(verbose_name='拓展问题')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
            ],
            options={
                'verbose_name': '问答信息',
                'verbose_name_plural': '问答信息',
            },
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('file_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='文件名')),
                ('file_path', models.FileField(storage=huawei.models.MyStorge(), upload_to='huawei', verbose_name='存储路径')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '文件上传',
            },
        ),
    ]
